Repository fossasia/neurolab-android, pull requests merged in 2019-08, with the labels that each got.

#386 Uniform Fonts and other UI updates
  app/src/main/res/layout/activity_focus_parent.xml
  app/src/main/res/layout/activity_meditation.xml
  app/src/main/res/layout/activity_meditation_home.xml
  app/src/main/res/layout/activity_meditation_list.xml
  app/src/main/res/layout/item_meditation_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Status: Review Required

#385 Focus Mode Pop-up Instruction-Actions
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
Labels: Status: Review Required

#393 Record Menu action updated and toggled
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/res/menu/focus_utility_menu.xml
Labels: Status: Review Required

#388 Parse channel data from recorded data to process
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
Labels: Status: Review Required

#394 Device Info screen connected
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/layout/device_instruction_layout.xml
Labels: Status: Review Required

#395 Implemented Snackbar Actions while recording and stopping
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/res/layout/activity_program_mode.xml
  app/src/main/res/layout/record_dialog_layout.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#408 fix: improved rocket animation and fixed initial startup
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
Labels: Fix

#413 UX/UI updates and improvs
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/layout/content_main.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/menu/focus_utility_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#415 Zoom/Drag feature enabled in PIN layout screen
  app/src/main/java/io/neurolab/activities/PinLayoutActivity.java
  app/src/main/res/layout/activity_pin_layout.xml
Labels: Status: Merge Ready

#416 fix: AboutUS screen and bug in data logger
  app/src/main/java/io/neurolab/activities/AboutUsActivity.java
  app/src/main/java/io/neurolab/activities/DataLoggerActivity.java
Labels: Fix

#422 Data processing and improvements in the Memory graph mode
  app/src/main/java/io/neurolab/communication/DataReceiver.java
  app/src/main/java/io/neurolab/communication/USBCommunicationHandler.java
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/fragments/StatisticsFragment.java
  app/src/main/res/layout/stat_items.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#421 Implemented Development mode in NeuroLab
  app/src/main/java/io/neurolab/activities/SettingsActivity.java
  app/src/main/java/io/neurolab/fragments/ConfigFragment.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/layout/content_main.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_config_settings.xml
Labels: Status: Merge Ready, Status: Review Required

#433 refactor: removed manifest warnings
  app/src/main/AndroidManifest.xml
Labels: Enhancement

#434 Implemented Focus media seekbar and timer
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
  app/src/main/res/layout/fragment_focus_visual.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#426 Pin descriptions enabled with dialog and colormap
  app/src/main/java/io/neurolab/activities/PinLayoutActivity.java
  app/src/main/java/io/neurolab/utilities/PinDetails.java
  app/src/main/res/drawable/dialog_body_background.xml
  app/src/main/res/drawable/dialog_header_background.xml
  app/src/main/res/drawable/neurolab_back_colormap.png
  app/src/main/res/drawable/neurolab_front_colormap.png
  app/src/main/res/layout/activity_pin_layout.xml
  app/src/main/res/layout/pin_description_dialog.xml
Labels: Status: Review Required

#436 Brushing up, Fixing bugs and fine tuning
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/card_focus.xml
  app/src/main/res/layout/card_meditation.xml
  app/src/main/res/layout/card_mem_graph.xml
  app/src/main/res/layout/card_relax.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#440 App icon updated
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_neurolab_app.xml
Labels: Enhancement

#444 Readme file updated with short desc about screenshots
  README.md
  docs/images/about_screen.jpeg
  docs/images/about_screen.png
  docs/images/home_screen.jpeg
  docs/images/home_screen.jpg
  docs/images/nav_menu.jpeg
  docs/images/nav_menu.png
  docs/images/start_screen_1.jpeg
  docs/images/start_screen_1.png
Labels: Enhancement, Status: Review Required
