Repository fossasia/neurolab-android, pull requests merged in 2019-07, with the labels that each got.

#335 Data Logger Activity for Memory Graph
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/activities/DataLoggerActivity.java
  app/src/main/java/io/neurolab/adapters/DataLoggerListAdapter.java
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/program_modes/MemoryGraphParent.java
  app/src/main/java/io/neurolab/utilities/FilePathUtil.java
  app/src/main/res/layout/activity_data_logger.xml
  app/src/main/res/layout/logged_data_item.xml
  app/src/main/res/menu/utility_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Status: Review Required

#342 Import Data Feature in Focus Mode
  app/src/main/java/io/neurolab/activities/DataLoggerActivity.java
  app/src/main/java/io/neurolab/activities/MemoryGraphParent.java
  app/src/main/java/io/neurolab/adapters/DataLoggerListAdapter.java
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/fragments/RelaxVisualFragment.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/java/io/neurolab/main/ProgramModeActivity.java
  app/src/main/java/io/neurolab/utilities/FilePathUtil.java
  app/src/main/res/layout/activity_data_logger.xml
  app/src/main/res/layout/fragment_focus_visual.xml
  app/src/main/res/menu/focus_utility_menu.xml
Labels: Status: Review Required

#345 Play and Stop feature in Focus mode
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
  app/src/main/res/menu/focus_utility_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#346 Save/Record, Program Info and Logged Data features in Focus Mode
  app/src/main/java/io/neurolab/activities/DataLoggerActivity.java
  app/src/main/java/io/neurolab/activities/ProgramModeActivity.java
  app/src/main/java/io/neurolab/adapters/DataLoggerListAdapter.java
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
  app/src/main/res/drawable/ic_record_stop_white.xml
  app/src/main/res/drawable/ic_record_white.xml
  app/src/main/res/menu/focus_utility_menu.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Status: Review Required

#351 Improvements in Menus and Nav Drawer
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/menu/main.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#352 Implemented Device Instructions Screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/activities/DeviceInstructionsActivity.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/drawable/icons8_usb_connected_100.png
  app/src/main/res/drawable/icons_usb_disconnected_100.png
  app/src/main/res/layout/device_instruction_layout.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement, Status: Review Required

#356 Implemented Meditation Home Screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/activities/FocusParentActivity.java
  app/src/main/java/io/neurolab/activities/MeditationHome.java
  app/src/main/java/io/neurolab/activities/ProgramModeActivity.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/drawable-xxhdpi/meditation_bg.jpg
  app/src/main/res/drawable/game_one_pic.png
  app/src/main/res/drawable/ic_depressed.xml
  app/src/main/res/drawable/ic_happiness.xml
  app/src/main/res/drawable/ic_happy_black.xml
  app/src/main/res/drawable/ic_lg_break.xml
  app/src/main/res/drawable/ic_sh_break.xml
  app/src/main/res/drawable/ic_sleep.xml
  app/src/main/res/drawable/ic_travel.xml
  app/src/main/res/font/montserrat.xml
  app/src/main/res/layout/activity_focus_parent.xml
  app/src/main/res/layout/activity_meditation_home.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#367 Fix: App Crash when importing from Logger directly
  app/src/main/java/io/neurolab/main/NeuroLab.java
Labels: Fix, Status: Review Required

#354 Implemented Focus Main Screen
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_focus_parent.xml
  app/src/main/res/menu/focus_utility_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#373 Fix[#369]: Updated Datasets
  datasets/Dataset1/Dataset1.csv
  datasets/Dataset10/Dataset10.csv
  datasets/Dataset11/Dataset11.csv
  datasets/Dataset12/Dataset12.csv
  datasets/Dataset13/Dataset13.csv
  datasets/Dataset14/Dataset14.csv
  datasets/Dataset15/Dataset15.csv
  datasets/Dataset16/Dataset16.csv
  datasets/Dataset17/Dataset17.csv
  datasets/Dataset18/Dataset18.csv
  datasets/Dataset19/Dataset19.csv
  datasets/Dataset2/Dataset2.csv
  datasets/Dataset20/Dataset20.csv
  datasets/Dataset21/Dataset21.csv
  datasets/Dataset22/Dataset22.csv
  datasets/Dataset23/Dataset23.csv
  datasets/Dataset24/Dataset24.csv
  datasets/Dataset25/Dataset25.csv
  datasets/Dataset26/Dataset26.csv
  datasets/Dataset27/Dataset27.csv
  datasets/Dataset28/Dataset28.csv
  datasets/Dataset29/Dataset29.csv
  datasets/Dataset3/Dataset3.csv
  datasets/Dataset30/Dataset30.csv
  datasets/Dataset31/Dataset31.csv
  datasets/Dataset32/Dataset32.csv
  datasets/Dataset33/Dataset33.csv
  datasets/Dataset34/Dataset34.csv
  datasets/Dataset4/Dataset4.csv
  datasets/Dataset5/Dataset5.csv
  datasets/Dataset6/Dataset6.csv
  datasets/Dataset7/Dataset7.csv
  datasets/Dataset8/Dataset8.csv
  datasets/Dataset9/Dataset9.csv
Labels: Status: Review Required

#374 Implemented Location/GPS Track feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/utilities/LocationTracker.java
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#368 [#363] Implemented Playback Screen
  app/src/main/java/io/neurolab/activities/MeditationActivity.java
  app/src/main/java/io/neurolab/activities/MeditationHome.java
  app/src/main/java/io/neurolab/activities/MeditationListActivity.java
  app/src/main/java/io/neurolab/adapters/MeditationListAdapter.java
  app/src/main/res/drawable/ic_pause_meditate.xml
  app/src/main/res/drawable/ic_person_black.xml
  app/src/main/res/drawable/ic_play_meditate.xml
  app/src/main/res/drawable/ic_refresh_meditate.xml
  app/src/main/res/layout/activity_meditation.xml
  app/src/main/res/layout/activity_meditation_home.xml
  app/src/main/res/layout/activity_meditation_list.xml
  app/src/main/res/layout/item_meditation_layout.xml
  app/src/main/res/raw/breathing_space_practice.mp3
  app/src/main/res/raw/calm_the_mind.mp3
  app/src/main/res/raw/easing_stress.mp3
  app/src/main/res/raw/soften_and_relax.mp3
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#362 Implemented Meditation List with playback functionality
  app/src/main/AndroidManifest.xml
Labels: Status: Review Required

#376 Transmit Data from SD card dataset with Arduino-Android
  app/src/main/java/io/neurolab/activities/TestModeActivity.java
  app/src/main/java/io/neurolab/communication/USBCommunicationHandler.java
Labels: Status: Review Required

#360 Updated focus screen
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
  app/src/main/res/layout/fragment_focus_visual.xml
  app/src/main/res/menu/focus_utility_menu.xml
  app/src/main/res/values/dimens.xml
Labels: Status: Merge Ready, Status: Review Required

#380 Data Logger in Nav drawer and improvements
  app/src/main/java/io/neurolab/activities/DataLoggerActivity.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/menu/activity_main_drawer.xml
Labels: Status: Merge Ready

#377 Implemented Data Record feature from Device
  app/src/main/java/io/neurolab/communication/USBReceiver.java
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/utilities/FilePathUtil.java
  arduino/sketch_read_transmit_from_sd/sketch_read_transmit_from_sd.ino
Labels: Status: Review Required

#382 Updated Data Logging with possible fields
  app/src/main/java/io/neurolab/communication/DataReceiver.java
  app/src/main/java/io/neurolab/communication/USBReceiver.java
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
Labels: Status: Review Required
