Repository fossasia/neurolab-android, pull requests merged in 2019-06, with the labels that each got.

#282 feat: images and layout changes for cards
  app/src/main/assets/fonts/circular_std_black.otf
  app/src/main/assets/fonts/circular_std_medium.otf
  app/src/main/res/drawable/bg_card_focus.xml
  app/src/main/res/drawable/bg_card_mem_graph.xml
  app/src/main/res/drawable/bg_card_relax.xml
  app/src/main/res/drawable/gradient_focus.xml
  app/src/main/res/drawable/gradient_mem_graph.xml
  app/src/main/res/drawable/gradient_relax.xml
  app/src/main/res/drawable/ic_card_focus.xml
  app/src/main/res/drawable/ic_card_mem_graph.xml
  app/src/main/res/drawable/ic_card_relax.xml
  app/src/main/res/layout/card_focus.xml
  app/src/main/res/layout/card_mem_graph.xml
  app/src/main/res/layout/card_relax.xml
  docs/images/card-backgrounds/bg_card_focus.svg
  docs/images/card-backgrounds/bg_card_mem_graph.svg
  docs/images/card-backgrounds/bg_card_relax.svg
Labels: Feature

#279 Revamping the UX/UI of the Launcher Screen
  app/src/main/java/io/neurolab/main/MainActivity.java
  app/src/main/java/io/neurolab/main/ProgramModeActivity.java
  app/src/main/res/drawable/focus_gradient.xml
  app/src/main/res/layout-land/content_main.xml
  app/src/main/res/layout/content_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Status: Review Required

#274 Completed the Android Arduino bridge testing
  app/src/main/java/io/neurolab/main/DeviceConnector.java
  app/src/main/java/io/neurolab/main/TestModeActivity.java
  app/src/main/res/layout/content_test_mode.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#277 Added the function for SD card data transfer
  arduino/sketch_read_transmit_from_sd.ino
  arduino/sketch_serial_echo.ino
Labels: Feature, Status: Review Required

#270 fix: Club Settings and Feedback Settings together
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/fragments/ConfigFragment.java
  app/src/main/java/io/neurolab/fragments/NeuroSettingsFragment.java
  app/src/main/java/io/neurolab/main/MainActivity.java
  app/src/main/java/io/neurolab/main/NeuroSettingsActivity.java
  app/src/main/java/io/neurolab/main/SettingsActivity.java
  app/src/main/java/io/neurolab/settings/ConfigsActivity.java
  app/src/main/java/io/neurolab/settings/FeedbackSettings.java
  app/src/main/res/layout/activity_configs.xml
  app/src/main/res/layout/activity_neurosettings.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/fragment_feedback_settings.xml
  app/src/main/res/menu/main.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/fragment_config_settings.xml
  app/src/main/res/xml/fragment_neuro_settings.xml
Labels: Fix

#285 docs: added neuro dataset
  arduino/sketch_read_transmit_from_sd/k24bit.csv
  arduino/sketch_read_transmit_from_sd/sketch_read_transmit_from_sd.ino
Labels: Status: Review Required

#286 Developing the Memory Graph Program UX
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/main/MainActivity.java
  app/src/main/java/io/neurolab/main/ProgramModeActivity.java
  app/src/main/java/io/neurolab/program_modes/MemoryGraphActivity.java
  app/src/main/res/layout/content_main.xml
  app/src/main/res/layout/fragment_memory_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#295 fix: travis build
  .travis.yml
Labels: Fix

#296 Data from datasets in MemoryGraph
  app/src/main/java/io/neurolab/communication/CommunicationHandler.java
  app/src/main/java/io/neurolab/main/MainActivity.java
  app/src/main/java/io/neurolab/program_modes/MemoryGraphActivity.java
Labels: Status: Conflicts, Status: Review Required

#319 Downgraded AppIntro for supporting older versions
  app/build.gradle
Labels: Fix

#313 Added the basic audio functionalities
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/main/MainActivity.java
  app/src/main/java/io/neurolab/main/output/audio/MediaPlayerHolder.java
  app/src/main/java/io/neurolab/main/output/audio/PlaybackInfoListener.java
  app/src/main/java/io/neurolab/main/output/audio/PlayerAdapter.java
  app/src/main/java/io/neurolab/program_modes/MeditationActivity.java
  app/src/main/res/layout/activity_meditation.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/raw/delta_waves.mp3
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#312 Import data feature in Memory Graph
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/program_modes/MemoryGraphActivity.java
  app/src/main/java/io/neurolab/utilities/FilePathUtil.java
  app/src/main/java/io/neurolab/utilities/PermissionUtils.java
  app/src/main/res/drawable/ic_import.xml
  app/src/main/res/layout/progress_dialog_layout.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/menu/utility_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#318 Minimal configs and singleton pattern for device communications
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/communication/USBCommunicationHandler.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/java/io/neurolab/program_modes/MemoryGraphActivity.java
  app/src/main/res/layout/app_bar_main.xml
Labels: Status: Review Required

#322 Parsed Statistics along with Memory Graph
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/fragments/SpectrumFragment.java
  app/src/main/java/io/neurolab/fragments/StatisticsFragment.java
  app/src/main/java/io/neurolab/main/ProgramModeActivity.java
  app/src/main/java/io/neurolab/model/DefaultFFTData.java
  app/src/main/java/io/neurolab/model/GenericFeedbackSettings.java
  app/src/main/java/io/neurolab/program_modes/MemoryGraphParent.java
  app/src/main/res/color/bottom_tab_item_foreground.xml
  app/src/main/res/drawable/ic_graph.xml
  app/src/main/res/drawable/ic_happy.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_sad.xml
  app/src/main/res/drawable/ic_spectrum.xml
  app/src/main/res/drawable/ic_stats.xml
  app/src/main/res/layout/activity_memory_graph_parent.xml
  app/src/main/res/layout/fragment_memory_graph.xml
  app/src/main/res/layout/fragment_spectrum.xml
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/layout/stat_items.xml
  app/src/main/res/menu/navigation_mem_graph.xml
  app/src/main/res/menu/utility_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#320 Added bluetooth connectivity to send and receive data in Android
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/communication/bluetooth/BluetoothConnectionManager.java
  app/src/main/java/io/neurolab/communication/bluetooth/BluetoothTestActivity.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/layout/activity_bluetooth_test.xml
  app/src/main/res/menu/activity_main_drawer.xml
Labels: Status: Review Required

#331 Implemented Stop Graph Feature
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/res/drawable/ic_stop.xml
  app/src/main/res/menu/utility_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#324 Density Spectrum Graph in Memory Graph
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/fragments/SpectrumFragment.java
  app/src/main/res/layout/fragment_spectrum.xml
  app/src/main/res/layout/spectrum_info_layout.xml
  app/src/main/res/menu/spectrum_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#334 Play/Resume feature in Memory Graph
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/res/drawable/ic_play.xml
  app/src/main/res/menu/utility_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required

#340 Removed unused resources
  app/src/main/res/drawable-v21/ic_menu_camera.xml
  app/src/main/res/drawable-v21/ic_menu_gallery.xml
  app/src/main/res/drawable-v21/ic_menu_manage.xml
  app/src/main/res/drawable-v21/ic_menu_slideshow.xml
  app/src/main/res/drawable/curve_background.xml
  app/src/main/res/drawable/focus_gradient.xml
  app/src/main/res/drawable/hill_background.jpg
  app/src/main/res/drawable/ic_file_black.xml
  app/src/main/res/drawable/ic_online_dot.xml
  app/src/main/res/drawable/ic_rocket_image.xml
  app/src/main/res/drawable/ic_starsfour.xml
  app/src/main/res/drawable/nl_logo.jpg
  app/src/main/res/layout/content_configs.xml
Labels: Status: Review Required

#338 Save/Record feature in Memory Graph
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  app/src/main/java/io/neurolab/utilities/FilePathUtil.java
  app/src/main/res/menu/utility_menu.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Required
