Repository fossasia/neurolab-android, pull requests merged in 2019-05, with the labels that each got.

#179 fix: Uninitialized sample file reference in FocusAudioFeedback class
  app/src/main/java/io/neurolab/output/audio/FocusAudioFeedback.java
Labels: fix

#193 feat: Added OSCReceiverFragment
  app/src/main/java/io/neurolab/network/OSCReceiverFragment.java
  app/src/main/res/layout/fragment_oscreceiver.xml
  app/src/main/res/values/strings.xml
Labels: feature

#195 feat: Adding the NFBServer class
  app/src/main/java/io/neurolab/NFBServer.java
Labels: feature

#141 chore: Update README.md and Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: chore

#147 feat: Add connect to device in navigation drawer
  app/src/main/res/menu/activity_main_drawer.xml
Labels: feature

#148 feat: Add a custom action bar
  app/src/main/res/drawable/curve_background.xml
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#160 Improvement of the class FocusAudioFeedback
  app/src/main/java/io/neurolab/main/NFBServer.java
  app/src/main/java/io/neurolab/main/output/audio/FocusAudioFeedback.java
Labels: conflicts

#189 feat: Implemented FFTPreprocessor
  app/src/main/java/io/neurolab/model/FFTPreprocessor.java
  app/src/main/java/io/neurolab/settings/NeuroSettings.java
Labels: feature

#231 fix:Back Arrow working in all modes.
  app/src/main/AndroidManifest.xml
Labels: fix

#246 feat: Implemented improved Focus- Rocket Screen
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/gui/CustomSpaceView.java
  app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
  app/src/main/res/drawable-nodpi-v4/bg_focus_background.jpg
  app/src/main/res/drawable/ic_indicator.xml
  app/src/main/res/drawable/ic_starsfour.xml
  app/src/main/res/drawable/ic_starsone.xml
  app/src/main/res/drawable/ic_starsthree.xml
  app/src/main/res/drawable/ic_starstwo.xml
  app/src/main/res/drawable/ic_startup.xml
  app/src/main/res/layout/fragment_focus_visual.xml
  app/src/main/res/values/colors.xml
Labels: feature

#254 fix: removed space to left in settings
  app/src/main/java/io/neurolab/fragments/NeuroSettingsFragment.java
  app/src/main/res/xml/neuro_settings_fragment.xml
Labels: fix, review-required

#269 Improved the UI by making consistent color scheme throughout and other fixes
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/main/TestModeActivity.java
  app/src/main/java/io/neurolab/settings/ConfigsActivity.java
  app/src/main/res/drawable/ic_offline_dot.xml
  app/src/main/res/drawable/side_nav_bar.xml
  app/src/main/res/layout/activity_configs.xml
  app/src/main/res/layout/activity_test_mode.xml
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: Enhancement, Status: Review Required
