Repository fossasia/neurolab-android, pull requests merged in 2019-10, with the labels that each got.

#495 fix: travis build for pr
  .travis.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: fix

#488 Fixed Meditation Bug
  app/src/main/java/io/neurolab/fragments/ConfigFragment.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
Labels: Status: Merge Ready, Status: Review Required

#486 feat : Add landscape screen for meditation activity.
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/activities/MeditationActivity.java
  app/src/main/res/layout-land/activity_meditation.xml
Labels: Status: Merge Ready, Status: Review Required, feature

#500 feature : added file sharing feature.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/neurolab/activities/ShareDataActivity.java
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/drawable/button_bg_rounded.xml
  app/src/main/res/layout/activity_share_data.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/filepaths.xml
Labels: feature

#509 feature : Add data share option from data logger screen.
  app/src/main/java/io/neurolab/activities/DataLoggerActivity.java
  app/src/main/res/menu/share_menu.xml
Labels: feature

#516 chore(deps): bump opencsv from 4.6 to 5.0
  app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
  app/src/main/java/io/neurolab/fragments/MemoryGraphFragment.java
  build.gradle
Labels: chore

#508 fix: Landscape screen of home screen
  app/src/main/res/layout-land/content_main.xml
Labels: fix

#518 feature : Add double tap app exit functionality.
  app/src/main/java/io/neurolab/main/NeuroLab.java
  app/src/main/res/values/strings.xml
Labels: feature
